services:
  - type: web
    name: metacraft-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/serviceAccountKey.json
      - key: ALLOWED_ORIGIN
        value: "*"
    secretFiles:
      - name: serviceAccountKey.json
        mountPath: /etc/secrets/serviceAccountKey.json
